name: CMake

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build-and-test-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Add LLVM Repository
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        
    - name: Install dependencies
      run: |
           sudo apt-get update
           sudo apt-get install -y cmake ninja-build clang-18 libfmt-dev libc++-18-dev libc++abi-18-dev
           sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
           sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
           
    - name: Configure Clang-18 as the default compiler
      run: |
        echo "CC=clang-18" >> $GITHUB_ENV
        echo "CXX=clang++-18" >> $GITHUB_ENV
        clang --version
        clang++ --version

    - name: Configure CMake with clang++-18 llvm libc++
      run: cmake -B ${{github.workspace}}/build/clang-18-libcxx -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_CXX_STANDARD=23
      
    - name: Build with clang++-18 llvm libc++
      run: cmake --build ${{github.workspace}}/build/clang-18-libcxx
      
    - name: Test with clang++-18 llvm libc++
      working-directory: ${{github.workspace}}/build/clang-18-libcxx
      run: ctest

    - name: Configure CMake with clang++-18 gnu libstdc++
      run: cmake -B ${{github.workspace}}/build/clang-18 -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_CXX_STANDARD=23
    - name: Build with clang++-18
      run: cmake --build ${{github.workspace}}/build/clang-18
    - name: Test with clang++-18
      working-directory: ${{github.workspace}}/build/clang-18
      run: ctest
      
  build-and-test-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install gcc-13
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13
        
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build libfmt-dev

    - name: Configure CMake with gcc
      run: cmake -B ${{github.workspace}}/build/gcc -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=g++-13 -DCMAKE_CXX_STANDARD=23
      
    - name: Build with gcc
      run: cmake --build ${{github.workspace}}/build/gcc
      
    - name: Test with gcc
      working-directory: ${{github.workspace}}/build/gcc
      run: ctest
